"""
Exported area modules.

Each ``<area>.py`` here is generated by the in-game |wbuild|n command's
``export`` verb (see :mod:`systems.areas`).  A module defines two module-level
names:

* ``ROOMS`` — a dict of ``room_key -> prototype dict`` (no location/dbref data).
* ``EXITS`` — a list of ``(from_key, direction, to_key, attrs)`` tuples, where
  ``from_key``/``to_key`` reference ``ROOMS`` keys (never dbrefs, which are not
  stable across a fresh world).

These files are the git-tracked source of truth for built world content.  Edit
them in-game and re-export, or hand-edit and reload — both round-trip through
:func:`systems.areas.load_area`.
"""
